### ISSUE TITLE
Custom type definitions not found in build

### ISSUE THREAD

**Issue by olivialeachclark** [teambit/bit#4757]
### Describe the bug
Defining custom type definitions via the `overrideBuildTsConfig` option no longer works. This worked in version `0.0.486`.

### Steps to Reproduce
Override the config and compiler options as follows:

```
// ...
const tsconfig = require('./typescript/tsconfig.json');
const compilerOptions = {
  types: [require.resolve("./types/anytype.d.ts")],
}

export class ReactExtension {
// ...

  static async provider([envs, react]: [EnvsMain, ReactMain]) {
    const newReactEnv = react.compose([
      react.overrideTsConfig(tsconfig, compilerOptions),
      react.overrideBuildTsConfig(tsconfig, compilerOptions),
    ]);
}
// ...
```

The type definitions are only available in the preview runtime, but not at build time. Running `bit build` throws type errors (e.g. `Property 'x' does not exist on type 'SomeType'`).

### Expected Behavior
Custom type definitions are available both in runtime and buildtime.

### Specifications
* Bit version: `0.0.488`
* Workspace type: harmony
* Node version: `v16.5.0`
* npm / yarn version: npm `7.19.1`
* Platform: mac

_for harmony workspace_

* relevant env: teambit/react
* relevant aspects: teambit/harmony

### Additional context
Relevant slack thread: https://bit-dev-community.slack.com/archives/CCDHG0TPY/p1626279429129000

**Comment by GiladShoham** [comment]
Is it only for the buildTsConfig or also for the tsConfig?
What about the tsconfig merge (first argument)

**Comment by ivansky** [comment]
Well it's the same issue here https://github.com/teambit/bit/discussions/4764

**Comment by GiladShoham** [comment]
It's indeed the same issue.
I'll fix it. It's a regression as a result of the new useTypescript api.
I'll also describe how to move to the new API
