### ISSUE TITLE
On fresh install with react-typescript compiler : Error TS2300 Duplicate identifier

### ISSUE THREAD

**Issue by jonathan-koskas** [teambit/bit#3129]
### Description

With a fresh workspace install, I try to use Bit.dev for the first time. My environement is` create-react-app` + `typescript` +` styled-components` + `storybook`.
When I try to build with `react-typescript@3.1.57` compiler, I've got bunch of Duplicate identifier errors.

### Specifications

- Bit version: 14.8.8
- Node version: 13.13.0
- npm / yarn version: 6.14.4 / 1.22.4
- Platform: Windows 10
- Bit compiler (include version): react-typescript@3.1.57
- Bit tester (include version): none

### Context and additional information

![image](https://user-images.githubusercontent.com/3208403/93715205-4752ca00-fb68-11ea-8e41-6f68be589f29.png)
Part of my `Package.json` file.

![image](https://user-images.githubusercontent.com/3208403/93715312-dc55c300-fb68-11ea-80b7-4b1c20a5650f.png)
errors

**Comment by alexanderkeller** [comment]
Same effect/problem in our project.

**Comment by Orancula** [comment]
Facing same issue

**Comment by Blazsoul** [comment]
Any update guys? keep getting this error while trying to tag components

**Comment by JoshK2** [comment]
It happens because @types/styled-components require @types/react-native and it's causing problems with DOM lib.
Downgrade to version 4.1.8 of @types/styled-components should solve it because it not require @types/react-native:
```
npm i @types/styled-components@4.1.8 --save-dev --save-exact
```
I'll soon publish a new version of React-typescript compiler that solve this issue without downgrading the @types/styled-components version, the compiler will remove the @types/react-native from the node_modules folder inside the build process of the component.

**Comment by JoshK2** [comment]
I published a new version of the React-typescript compiler to solve this issue:
https://bit.dev/bit/envs/compilers/react-typescript?version=3.1.63
