### PR TITLE
fix(isolator): isolate cyclic dependencies of seeders to avoid registry fetch

### PR DESCRIPTION
**Pull request by zkochan**
## Summary

Fixes the circular-dependency build failure seen consistently on Ripple, where the build tries to install a cycle member from the registry that isn't published yet:

```
GET https://node-registry.bit.cloud/@<scope>%2Fcomp1: Not Found - 404
@<scope>/comp1@0.0.0-<hash> is not in the npm registry  (ERR_PNPM_FETCH_404)
```

### Root cause

`bit sign` isolates components in **`seedersOnly`** mode — only the components being signed get capsules; every *dependency* is installed as an npm package from the registry. That breaks for a dependency in a **cycle** with a seeder: the cyclic component references back into a seeder whose snap-version package was never published, so the capsule install 404s.

It only reproduces on a real hub/lane (locally, remotes are registered and workspace components link locally), which is why it's Ripple-specific.

### Fix (`scopes/component/isolator/isolator.main.runtime.ts`)

- **seedersOnly path** — new `getCyclicDependenciesOfSeeders`: build the seeder graph, use `graph.findCycles()` (the graph is seeded, so this returns seeder-involving cycles), and pull those cyclic dependency components into `componentsToIsolate` so they become real capsules linked locally instead of fetched.
- **non-seedersOnly path** (`bit build`) — `filterUnmodifiedExportedDependencies` now takes `idsInCycle` and never excludes a component that's part of a seeder cycle from capsule creation, closing the same gap for built+exported cyclic deps.

## Test plan

- [x] `npm run lint` (tsc + oxlint) clean.
- [x] Reproduced via the sign-from-scope flow (lane, `comp1 ↔ comp2` cycle, snap both pending + export, sign one alone). **Without** the fix: `ERR_PNPM_FETCH_404` on the unpublished cyclic snap. **With** the fix: signs `succeed`, cyclic dep isolated as a capsule and linked locally.
- [x] Regression test added to the `sign` command spec ("signing one member of a circular dependency while the other is still pending"). The `sign` command lives in its own repo, so that test is committed there, not in this PR.

## Notes

`getCyclicDependenciesOfSeeders` builds the seeder graph on every seedersOnly isolation. It's cheap relative to the full sign (capsule writes + install + tasks), but can be gated behind a lighter pre-check if preferred.

### CODE REVIEW

**Comment by zkochan** [comment]
Good catch on the version-mismatch (Qodo "Cycle ids version mismatch"). Fixed in 1f61a04: cycle detection now uses `graph.findCycles(undefined, true)` (includeDeps) instead of the default, so it no longer depends on matching the (possibly versionless) seeder ids against the graph's versioned node ids. The graph is built from `getGraphIds(seeders)`, so it only spans the seeders and their dependencies — every cycle in it is one a seeder participates in, which is exactly what we want to keep as capsules.

**Comment by zkochan** [comment]
The CI failures (`e2e_test` → `bit new react` EnvNotFound `documenter-react@0.0.1`, and `bit_pr` → `core-aspect-env`) were caused by the fix being too broad. Narrowed in 4296091:

- Reverted the `filterUnmodifiedExportedDependencies` (workspace `createGraph`) change. Keeping published cyclic deps as capsules there forced loading their env (which isn't installed in that context) instead of installing them as plain packages.
- Gated the seeders-only cyclic-dep isolation to `!opts.context?.aspects`, so aspect loading (which is `seedersOnly: true`) no longer pulls cyclic aspect deps / loads `core-aspect-env`.

The fix now only applies to the `seedersOnly && !aspects` path — sign / tag-snap-from-scope / `bit capsule create --seeders-only` — which is exactly where the unpublished-snap registry fetch happens. `bit new react` and `bit ci pr` build via the workspace graph path, which the fix no longer touches. The `isolate-cyclic-deps` e2e test still passes.

File: scopes/component/isolator/isolator.main.runtime.ts [hunk 1]
```diff
@@ -365,9 +365,19 @@ export class IsolatorMain {
...
-    const componentsToIsolate = opts.seedersOnly
+    let componentsToIsolate = opts.seedersOnly
       ? await host.getMany(seeders)
       : await this.createGraph(seeders, createGraphOpts);
+    if (opts.seedersOnly) {
+      // seedersOnly skips the dependency graph and installs deps as packages from the registry.
+      // Dependencies that are in a cycle with a seeder can't be installed that way (their
+      // snap-version isn't published yet), so pull them into the isolation as capsules.
+      const cyclicDeps = await this.getCyclicDependenciesOfSeeders(seeders, componentsToIsolate, createGraphOpts);
+      if (cyclicDeps.length) {
```
[the remark this answers is not in the document]
Comment (zkochan) [reply scopes/component/isolator/isolator.main.runtime.ts]: Addressed in 1f61a04 and the surrounding rework: cycle detection now uses `graph.findCycles(undefined, true)` (includeDeps), which bypasses `ComponentIdGraph`'s seeder-id filtering entirely — so it no longer depends on matching (possibly versionless) seeder ids against versioned graph node ids. The `idsInCycle` set this comment refers to (on the `createGraph`/`filterUnmodifiedExportedDependencies` path) was removed in 4296091. The remaining `getCyclicDependenciesOfSeeders` derives ids straight from the graph nodes (`graph.node(idStr).attr`) and only compares against `alreadyIsolated` (resolved, versioned components), so there's no versionless/versioned mismatch.

File: scopes/component/isolator/isolator.main.runtime.ts [hunk 2]
```diff
@@ -365,9 +365,21 @@ export class IsolatorMain {
...
+    // published yet), so pull it into the isolation as a capsule. Skip this for aspect isolation:
+    // aspects are loaded from already-published packages and pulling cyclic aspect deps in only
+    // forces loading envs that aren't installed in that context.
+    if (opts.seedersOnly && !opts.context?.aspects) {
+      const cyclicDeps = await this.getCyclicDependenciesOfSeeders(seeders, componentsToIsolate, createGraphOpts);
+      if (cyclicDeps.length) {
+        this.logger.debug(`isolateComponents, adding ${cyclicDeps.length} cyclic dependencies of the seeders`);
+        componentsToIsolate = [...componentsToIsolate, ...cyclicDeps];
+      }
+    }
```
[the remark this answers is not in the document]
Comment (zkochan) [reply scopes/component/isolator/isolator.main.runtime.ts:382]: This is intentional, and the suggested fix (threading `idsInSeederCycle` into `filterUnmodifiedExportedDependencies`) is exactly what an earlier revision of this PR did — it broke CI and was reverted in 4296091.

The problem: `filterUnmodifiedExportedDependencies` excludes *published* cyclic deps too (e.g. `teambit.documenter/ui/label`, whose env is `documenter-react@0.0.1`). Force-keeping those as capsules makes the build load their env, which isn't installed in that context, so `bit new react` and `bit ci pr` failed with `EnvNotFound` / `failed loading env core-aspect-env`. The blanket "never exclude a cycle member" rule therefore causes a worse, broader regression than the narrow case it guards against.

Two more points:
1. No regression: on master the non-seedersOnly path already excludes cyclic deps. This PR doesn't change that path — it only *adds* protection to the seeders-only path, which is where the Ripple failure actually occurs (`bit sign` / tag-snap-from-scope isolate seeders-only).
2. The non-seedersOnly 404 is narrower than it looks: workspace cycle members are linked locally (`file:`); it can only bite an *imported, non-workspace* cyclic dep pinned to an unpublished snap. Handling that safely needs to distinguish unpublished from published cyclic deps (so we don't force-load envs of the published ones) — a targeted follow-up, not a blanket keep-all. Happy to do that separately if it's hit in practice.

**Comment by zkochan** [comment]
Heads up: the `Cannot find module '@teambit/legacy'` failure (691 tests) wasn't from this change — a previous `Merge branch 'master'` mis-resolved `pnpm-lock.yaml` and `.bitmap`, leaving the dependency tree inconsistent so the bit CLI couldn't resolve `@teambit/legacy` (every `bit link`/`install`/`tag` failed).

I've rebuilt the branch cleanly: the four isolator commits replayed onto current master (1.13.242), dropping the bad merges. The net diff is now only the two files it should be:

- `scopes/component/isolator/isolator.main.runtime.ts`
- `e2e/harmony/isolate-cyclic-deps.e2e.ts`

No `pnpm-lock.yaml` / `.bitmap` / unrelated edits. Force-pushed (force-with-lease against the corrupted head). Please re-run CI on the new head `782a20cc9`.

**Review by GiladShoham — APPROVED** [review]
